version: "3"

services:
  app:
    build:
      context: ./
    container_name: strapi_app
    ports:
      - 1337:1337
  nginx:
    image: nginx:latest
    container_name: strapi_nginx_app
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: curl --fail http://localhost:1337 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
