FROM node:18.16.0
#FROM strapi/base

WORKDIR usr/src/app

COPY ./package*.json ./

RUN npm install -g npm@9.5.1

RUN npm install

COPY ./.env.dev ./.env

COPY . .

# RUN npm run build

EXPOSE 1338

CMD ["npm","run","dev"]